---
- hosts: nodes_proxmox
  become: true
  tasks:
    - name: Mount an NFS volume
       ansible.posix.mount:
         src: 192.168.1.XXX:/nfs/ssd/shared_data # Change this for the nas ip address
         path: /mnt/nfs
         opts: rw,sync,hard,intr
         state: mounted
         fstype: nfs