apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-conf
data:
  apache.conf: |
    ##
    ##
    ## Apache config file should be here
    ##
    ## 
  virtualhost.conf: |
    ##
    ##
    ## Place more config here
    ##
    ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.52-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/apache # mount apache-conf volumn to /etc/apache
          readOnly: true
          name: apache-conf
        - mountPath: /var/log/apache
          name: log
      volumes:
      - name: apache-conf
        configMap:
          name: apache-conf # place ConfigMap `apache-conf` on /etc/apache
          items:
            - key: apache.conf
              path: apache.conf
            - key: virtualhost.conf
              path: virtualhost/virtualhost.conf # dig directory
      - name: log
        emptyDir: {}

  
